#!/bin/sh

IMAGE_TO_USE="sys42/docker-go-builder:latest"

TMPENV=""
[ -n "$GOOS" ]        && TMPENV="-e GOOS=$GOOS"
[ -n "$GOARCH" ]      && TMPENV="$TMPENV -e GOARCH=$GOARCH"
[ -n "$CGO_ENABLED" ] && TMPENV="$TMPENV -e CGO_ENABLED=$CGO_ENABLED"
[ -n "$GOBIN" ]       && TMPENV="$TMPENV -e GOBIN=$GOBIN"
[ -n "$GOVENDOR" ]    && TMPENV="$TMPENV -e GOVENDOR=$GOVENDOR"

[ -n "$DEBUG" ] && TMPENV="$TMPENV -e DEBUG=$DEBUG" && echo "TMPENV = [$TMPENV]"

docker run -ti --rm -v $PWD:/src -w /src $TMPENV "$IMAGE_TO_USE" \
       remapuser app $(id -u) $(id -g) goenv "$@"
