#!/bin/sh

IMAGE_TO_USE="sys42/docker-go-builder:latest"

TMPENV=""
[ -n "$GOOS" ]        && TMPENV="-e GOOS=$GOOS"
[ -n "$GOARCH" ]      && TMPENV="$TMPENV -e GOARCH=$GOARCH"
[ -n "$CGO_ENABLED" ] && TMPENV="$TMPENV -e CGO_ENABLED=$CGO_ENABLED"

# experimental: perform no path magic and other stuff
if [ -n "$NOMAGIC" ]; then
	TMPENV="$TMPENV -e NOMAGIC=$NOMAGIC"
    [ -n "$GOPATH" ] && TMPENV="$TMPENV -e GOPATH=$GOPATH"
    [ -n "$GOBIN" ]  && TMPENV="$TMPENV -e GOBIN=$GOBIN"
fi

[ -n "$TRACE" ] && TMPENV="$TMPENV -e TRACE=$TRACE" && echo "TMPENV = [$TMPENV]"

docker run -ti --rm -v $PWD:/app -w /app $TMPENV "$IMAGE_TO_USE" \
       remapuser app $(id -u) $(id -g) goexec "$@"
