#!/bin/bash
set -uo pipefail

#trap 'echo "[ERROR] exitcode=$?" >&2' ERR

TRACE=${TRACE:-""}
NOMAGIC=${NOMAGIC:-""}

err_exit() {
	echo "[ERROR] $1" >&2
	exit $2
}

if [ -z "$NOMAGIC" ]; then
	FILE_MAIN=$(grep -l -s 'func\s*main' *.go)

	[ -z "$FILE_MAIN" ] && err_exit "file with 'package main' not found" 2
	[ $(echo "$FILE_MAIN" | wc -l) -gt 1 ] && err_exit "more than one file with 'package main' found" 3

	FILE_BIN=${FILE_MAIN/.go/}
	DIR_WORK=$(pwd)
	DIR_VENDOR="$DIR_WORK"/third-party
	DIR_BIN="$DIR_WORK"/bin

	HELPERPATH=/go/src/x/y/
	mkdir -p "$HELPERPATH"
	HELPERPATH="$HELPERPATH"/"$FILE_BIN"
	ln -s "$DIR_WORK" "$HELPERPATH"
	cd "$HELPERPATH"

	export GOPATH="$DIR_VENDOR":/go
	export GOBIN="$DIR_BIN"
fi

[ -n "$TRACE" ] && env

"$@"
